version: "2"
linters:
  enable:     
    - intrange   
    - perfsprint
    - gocritic
    - errcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true  
    unused:
      parameters-are-used: false